#!/usr/bin/env python3
"""Turn an allocation (harness/allocate.py --emit) into an llm-compressor recipe.

One regex per (format, unit kind) listing its layers explicitly — no overlapping targets
(compressed-tensors resolves overlaps by target order, easy to get wrong). bf16 units are
simply not targeted. Embedding option 'fp8w' is emitted as INT8 per-row weight-only: that is
what vLLM 0.28 can serve for embeddings (dequant-on-lookup, WNA16 INT); its error is the
same order as the FP8 per-row proxy the scan measured.
Usage: python3 harness/emit_recipe.py results/alloc-X.json recipes/rX.yaml
"""
import json, sys

MOD = {"gdn.qkvz": r"linear_attn\\.(in_proj_qkv|in_proj_z)", "gdn.out": r"linear_attn\\.out_proj",
       "attn.qkv": r"self_attn\\.(q|k|v)_proj", "attn.o": r"self_attn\\.o_proj",
       "mlp.gate_up": r"mlp\\.(gate|up)_proj", "mlp.down": r"mlp\\.down_proj"}
GROUP = 4
W8A8 = ('weights: {num_bits: 8, type: float, strategy: channel, symmetric: true, dynamic: false, observer: memoryless_minmax}\n'
        '          input_activations: {num_bits: 8, type: float, strategy: token, symmetric: true, dynamic: true}')
W4A4 = ('weights: {num_bits: 4, type: float, strategy: tensor_group, group_size: 16, symmetric: true, dynamic: false, scale_dtype: float8_e4m3fn, actorder: static}\n'
        '          input_activations: {num_bits: 4, type: float, strategy: tensor_group, group_size: 16, symmetric: true, dynamic: local, observer: static_minmax, scale_dtype: float8_e4m3fn}')


def main(alloc_file, out):
    al = json.load(open(alloc_file))["alloc"]
    targets = {"fp8": {}, "nvfp4": {}}
    for u, f in al.items():
        if f not in targets or u in ("embed",):
            continue
        if u == "lm_head":
            targets[f].setdefault("lm_head", None); continue
        band, kind = u.split(".", 1)
        layers = range(int(band[1:]) * GROUP, int(band[1:]) * GROUP + GROUP) if band[0] == "B" else [int(band[1:])]
        targets[f].setdefault(kind, set()).update(layers)
    def tlist(f):
        out = []
        for kind, layers in sorted(targets[f].items()):
            if kind == "lm_head":
                out.append('"re:.*lm_head"')
            else:
                ls = "|".join(str(l) for l in sorted(layers))
                out.append(f'"re:.*layers\\\\.({ls})\\\\.{MOD[kind]}$"')
        return out
    groups = ""
    for name, f, scheme in (("fp8", "fp8", W8A8), ("nvfp4", "nvfp4", W4A4)):
        t = tlist(f)
        if t:
            groups += f"        {name}:\n          targets:\n" + "".join(f"            - {x}\n" for x in t) + f"          {scheme}\n"
    embed = al.get("embed") == "fp8w"
    y = [f"# Generated by harness/emit_recipe.py from {alloc_file}",
         f"# budget {json.load(open(alloc_file))['budget_mib']:.0f} MiB (scanned units), sum-KL estimate "
         f"{json.load(open(alloc_file))['sum_kl']:.3e} vs R0 {json.load(open(alloc_file))['r0_sum_kl']:.3e}",
         "quant_stage:", "  quant_modifiers:"]
    if embed:   # written after GPTQ by harness/embed_int8.py (llm-compressor's embedding quant is broken)
        y.insert(2, "# embed_tokens -> INT8 per-row: post-step harness/embed_int8.py (not in this recipe)")
    y += ["    GPTQModifier:", "      block_size: 128", "      dampening_frac: 0.01",
          '      ignore: ["re:.*visual.*", "re:^mtp.*", "re:.*linear_attn\\\\.in_proj_(a|b)$"]',
          "      config_groups:", groups.rstrip("\n"),
          "      kv_cache_scheme: {num_bits: 8, type: float, strategy: tensor, symmetric: true, dynamic: false, observer: static_minmax}"]
    open(out, "w").write("\n".join(y) + "\n")
    print(open(out).read())


if __name__ == "__main__":
    main(*sys.argv[1:3])
